### ISSUE TITLE
✨ 是否可以增加功能：只下载弹幕

### ISSUE THREAD

**Issue by dongshuyan** [yutto-dev/bilili#109]
## 特性描述

目前工具我想下载弹幕，就必须要下载视频本身。有没有什么方法，可以只下载弹幕资源呢？~

**Comment by zjns** [comment]
我 fork 的作者的 yutto 项目 extended 分支添加了这个选项，`--subtitle-only` 或者 `-so`就可以只下载字幕。

**Comment by lecymeng** [comment]
> 我 fork 的作者的 yutto 项目 extended 分支添加了这个选项，`--subtitle-only` 或者 `-so`就可以只下载字幕。

翻了一下 repo 没看到 fork 的 repo 哇

**Comment by MiuKaShi** [comment]
> > 我 fork 的作者的 yutto 项目 extended 分支添加了这个选项，`--subtitle-only` 或者 `-so`就可以只下载字幕。
> 
> 翻了一下 repo 没看到 fork 的 repo 哇

这是zjns fork的 https://github.com/zjns/yutto，直接git下安装就行。
如果你是arch对应的PKGBUILD文件在这https://gist.github.com/MiuKaShi/39e108fd4acd66d533447c9bebe7c2ea。
