### ISSUE TITLE
🐛 无法下载，原因：「-412」 请求被拦截

### ISSUE THREAD

**Issue by 2689380792** [yutto-dev/bilili#143]
### 问题简述

![image](https://user-images.githubusercontent.com/59050529/165097768-554f2ff6-f6a7-4308-871e-80d2ef0036e9.png)

### 复现方式

bilili 或 bilili -c 都会被拦截 -412

### 环境信息

-  OS: 操作系统类型及其版本号 【Windows 11家庭中文版 21H2  22000.613】
-  Python: Python 版本号           【Python 3.8.5】
-  bilili: bilili 版本号                     【bilili 1.4.9】
-  FFmpeg: FFmpeg 版本号        【ffmpeg version N-104402-g2aa343bb6f-20211021 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10-win32 (GCC) 20210408】
-  如果是显示相关问题
    -  Shell: Shell 类型 (`echo $SHELL`)
    -  Terminal: 终端类型
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/bilili) 与[文档](https://bilili.nyakku.moe/)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 bilili 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/bilili/issues) 和 [discussion](https://github.com/yutto-dev/bilili/discussions) 中并没有重复问题

**Comment by Charlie-Ping** [comment]
我也是这个情况

**Comment by 2689380792** [comment]
> emmmm，是所有视频都这样吗？给个例子链接呗……

一年前我开始用bilili，都是满速下载。前几天所有视频突然不行了，被拦截，你自己不会用命令试一下吗

**Comment by SigureMo** [comment]
emmmm，我才反应过来是 1.4.9……在 issue 里搜关键词 `-412` 啊……很容易找到 #111 吧……

升级 1.4.10 应该就能解决

**Comment by SigureMo** [comment]
> > emmmm，是所有视频都这样吗？给个例子链接呗……
> 
> 一年前我开始用bilili，都是满速下载。前几天所有视频突然不行了，被拦截，你自己不会用命令试一下吗

？？？你觉得我作为一个维护者在问出问题之前会不先去尝试吗？？？反而是你，有仔细看 issue 的表格吗，就随便勾选？

> - [x] 本 issue 在 [issues](https://github.com/yutto-dev/bilili/issues) 和 [discussion](https://github.com/yutto-dev/bilili/discussions) 中并没有重复问题

这是让你确保在不麻烦别人的情况下自己解决问题，而不是为了给你提 issue 做限制，在提 issue 之前都不搜索一下吗？

**Comment by 2689380792** [comment]
> > > emmmm，是所有视频都这样吗？给个例子链接呗……
> > 
> > 
> > 一年前我开始用bilili，都是满速下载。前几天所有视频突然不行了，被拦截，你自己不会用命令试一下吗
> 
> ？？？你觉得我作为一个维护者在问出问题之前会不先去尝试吗？？？反而是你，有仔细看 issue 的表格吗，就随便勾选？
> 
> > * [x]  本 issue 在 [issues](https://github.com/yutto-dev/bilili/issues) 和 [discussion](https://github.com/yutto-dev/bilili/discussions) 中并没有重复问题
> 
> 这是让你确保在不麻烦别人的情况下自己解决问题，而不是为了给你提 issue 做限制，在提 issue 之前都不搜索一下吗？

因为这确实是个新的问题，他那个问题我在挂vpn的时候也会报错，前几天突然被拦截我就知道出意外了，我刚升级了1.4.10也没有用
![image](https://user-images.githubusercontent.com/59050529/165581087-1b159e59-561a-45e8-90e4-fe83817fc7ad.png)

**Comment by SigureMo** [comment]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/38436475/165582524-a55beb02-ce73-460e-97c5-e21200699637.png">

我这里完全没遇到这个问题，不好排查，你先试试加上 `--disable-proxy` 选项看看与代理是否相关吧

**Comment by 2689380792** [comment]
> <img alt="image" width="500" src="https://user-images.githubusercontent.com/38436475/165582524-a55beb02-ce73-460e-97c5-e21200699637.png">
> 
> 我这里完全没遇到这个问题，不好排查，你先试试加上 `--disable-proxy` 选项看看与代理是否相关吧
我应该是被b站拉黑了吧
![image](https://user-images.githubusercontent.com/59050529/165583998-dcdb59c7-a9aa-4820-a77c-e4a3c0d91e07.png)

**Comment by Charlie-Ping** [comment]
我更新了1.4.10, 貌似已经没有这个问题了

**Comment by TransouL** [comment]
@SigureMo
@SigureMo
作者您好，之前一直在用bilili，太好用了
不过最近又遇到了这个问题，尝试更新到了1.4.12，也尝试重新安装了2022-09-07的版本，都有这个问题
我这里还是Win7的老电脑，没办法升级到python3.9，所以暂时也不能尝试yutto
麻烦有时间的时候，帮忙看看能否解决吧，非常感谢！

**Comment by SigureMo** [comment]
> 作者您好，之前一直在用bilili，太好用了
> 不过最近又遇到了这个问题，尝试更新到了1.4.12，也尝试重新安装了2022-09-07的版本，都有这个问题
> 我这里还是Win7的老电脑，没办法升级到python3.9，所以暂时也不能尝试yutto
> 麻烦有时间的时候，帮忙看看能否解决吧，非常感谢！

不是我不想解决啊，是给我的信息不足，我无法定位问题，而且我这里一切正常，甚至无法复现问题……

**Comment by 2689380792** [comment]
> @SigureMo @SigureMo 您好，在使用作者问题之前，这里的赞了 不过最近又遇到了这个问题，尝试更新到了 1.4.12，也尝试重新安装了 2022-09-07 的版本，还有 我还是 Win7的老电脑也暂时不能尝试升级到python3.9，尝试升级 有时间的感谢，帮忙看看没解决吧，非常！

这个问题，大概率是B站标记了你（原因不知），我当时出现这问题后啥也没动过了几天还是半个月又能下载了，到现在还没复发过

**Comment by TransouL** [comment]
谢谢两位，我再试试看

**Comment by CcgKaneki** [comment]
用的是最新的版本，Mac电脑下载没问题，ubuntu系统的一直报这个错，用的是最新的1.4.12版本

**Comment by CcgKaneki** [comment]
最新版本1.4.12，Windows和Mac电脑都是正常下载的，只有ubuntu系统报错了
 WARN  以非大会员身份登录，无法下载会员专享剧集的喔～
一口气看完沙雕爆笑修仙动画《万倍返还系统》全集
全 1 话
已选择第 1 话
 WARN  一口气看完沙雕爆笑修仙动画《万倍返还系统》全集 无法下载，原因：「-412」 请求被拦截
 INFO  没有需要下载的视频！
<img width="1440" alt="截屏2022-11-14 下午5 07 40" src="https://user-images.githubusercontent.com/17875330/201620283-980f7dca-2112-48a0-a10b-08c864c764f8.png">

<img width="1067" alt="截屏2022-11-14 下午5 07 24" src="https://user-images.githubusercontent.com/17875330/201620307-e9f560a5-c5d3-4a7f-9324-392bc151b5a1.png">

**Comment by SigureMo** [comment]
> 最新版本1.4.12，Windows和Mac电脑都是正常下载的，只有ubuntu系统报错了

注意保护隐私，SESSDATA 已经帮你打码了

按理说这个问题与操作系统无关，问题应该只发生在网络环境差异上，因此回复和之前一样……

**Comment by WhileKing** [comment]
@TransouL 你的下载频率很高吗？

**Comment by CcgKaneki** [comment]
> 

在ubuntu上第一次用就失败了，昨天在ubuntu上第一次安装使用，是腾讯云的服务器

**Comment by CcgKaneki** [comment]
> 

感谢作者大大的解答。我的ubuntu是腾讯云的云服务器，网络也不知道是啥问题，下载部署都是正常的。我自己的电脑一个Mac一个windows倒是能正常使用。
