### ISSUE TITLE
✨ 无法下载，原因：「-412」 请求被拦截

### ISSUE THREAD

**Issue by liyuan3210** [yutto-dev/bilili#164]
### 特性描述

无法下载，原因：「-412」 请求被拦截,无法下载

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/bilili) 与[文档](https://bilili.nyakku.moe/)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/bilili/issues) 和 [discussion](https://github.com/yutto-dev/bilili/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
Close due to duplicate with #143
