### ISSUE TITLE
✨ 請問能不能直接使用1080p 高清下載?

### ISSUE THREAD

**Issue by seq2193** [yutto-dev/bilili#172]
### 特性描述

選擇 -t 112  80 似乎都只能 360或是 480p 
能不能默認都選1080p呢? 謝謝!

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/bilili) 与[文档](https://bilili.nyakku.moe/)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/bilili/issues) 和 [discussion](https://github.com/yutto-dev/bilili/discussions) 中并没有重复问题

**Comment by WhileKing** [comment]
要看原视频是否有1080p， 还有是否限制大会员才能看1080噢。

**Comment by seq2193** [comment]
https://fishaudio.github.io/fish-diffusion/pages/config.html#  看了這篇改了結構  還是沒跑出npy文件

**Comment by WhileKing** [comment]
> https://fishaudio.github.io/fish-diffusion/pages/config.html# 看了這篇改了結構 還是沒跑出npy文件

?这个和1080p有啥关系吗
1. 检查是否带了大会员cookie
2. 你要下载的剧是否有1080p

建议可以贴个链接和截图

**Comment by seq2193** [comment]
抱歉  回錯貼文了  https://www.bilibili.com/video/BV1os411r7Bj

**Comment by seq2193** [comment]
![Uploading 擷取.PNG…]()

**Comment by seq2193** [comment]
![擷取](https://user-images.githubusercontent.com/109962092/222320605-399847c4-8e97-4fbf-aa73-1354c56a3d99.PNG)

**Comment by WhileKing** [comment]
![image](https://user-images.githubusercontent.com/7239380/222371257-94decca4-32d1-4394-835a-8d87d0b72da4.png)
你没有设置sessdata，这个不需要大会员，但是需要登录

**Comment by seq2193** [comment]
!bilili  -q 116 --sess-data 6a8a0b0d%2C1688972468%2C242ca%2A11 https://www.bilibili.com/video/BV1os411r7Bj  謝謝  我成功了

**Comment by seq2193** [comment]
你好 我在b站發現我的動態被別人發文了，難道 session 洩漏別人就能登入我的帳號嗎？那麼我的密碼已經洩漏了嗎？

**Comment by WhileKing** [comment]
> 你好 我在b站發現我的動態被別人發文了，難道 session 洩漏別人就能登入我的帳號嗎？那麼我的密碼已經洩漏了嗎？

密码没泄露，只是你的这次登录信息被泄露了。 保险起见重新登录并更换密码吧，抱歉，上次忘记提醒你删除了

**Comment by seq2193** [comment]
我昨天哪個人在我的動態發文說 I AM LEAKED
還有
INFORM: YOUR CREDENTIAL IS LEAKED, HAS NOTHING TO DO WITH ANY VIDEOS
我於是多次登出再登入  SESSDATA 已經完全不同
沒關係 是我疏忽了,不好意思,我想說可能是來這裡看到這篇的人進到我的動態發貼的

**Comment by WhileKing** [comment]
> 我昨天哪個人在我的動態發文說 I AM LEAKED 還有 INFORM: YOUR CREDENTIAL IS LEAKED, HAS NOTHING TO DO WITH ANY VIDEOS 我於是多次登出再登入 SESSDATA 已經完全不同 沒關係 是我疏忽了,不好意思,我想說可能是來這裡看到這篇的人進到我的動態發貼的

过了有效期应该就没事了，b站对之前的sessdata可能没做处理，可能多次登录产生的凭证在有效期内都可用
