### ISSUE TITLE
请问一下仅下载弹幕功能被移除了吗?如果没有，可否给出一个命令示例，万分感谢！

### ISSUE THREAD

**Issue by Justin3298** [yutto-dev/bilili#277]
### 问题简述

想只下载弹幕，在issue搜了一下，发现有这个功能。但是我写命令一直报错，而且usage里也没有出现相关的参数，故来提问。

### 复现方式

bilili https://www.bilibili.com/video/BV1dX4y1R78D --danmaku-only true

### 环境信息

-  OS: win10
-  Python: Python 版本号  3.8.18
-  bilili: bilili 版本号  1.4.15
-  FFmpeg: FFmpeg 版本号 4.2.2

-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/bilili) 与[文档](https://bilili.nyakku.moe/)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 bilili 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/bilili/issues) 和 [discussion](https://github.com/yutto-dev/bilili/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
> 在issue搜了一下，发现有这个功能

bilili 从没支持过这个功能，支持的是 yutto
