### ISSUE TITLE
✨ 非常棒，但是番剧只能下载480画质的吗

### ISSUE THREAD

**Issue by YuYue1214** [yutto-dev/bilili#299]
### 特性描述

✨ 非常棒，但是番剧只能下载480画质的吗

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/bilili) 与[文档](https://bilili.nyakku.moe/)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/bilili/issues) 和 [discussion](https://github.com/yutto-dev/bilili/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
不登录只有 480P
