### ISSUE TITLE
下载异常

### ISSUE THREAD

**Issue by lidiwo** [yutto-dev/bilili#322]
### 问题简述

https://www.bilibili.com/bangumi/media/md28223043/
![Image](https://github.com/user-attachments/assets/976e9510-dbe4-400b-a3b4-8b1162e328cf)

### 复现方式

bilili https://www.bilibili.com/bangumi/media/md28223043/

### 环境信息

-  OS: 操作系统类型及其版本号
-  Python: Python 版本号 (`python --version`)
-  bilili: bilili 版本号 (`bilili -v`)
-  FFmpeg: FFmpeg 版本号 (`ffmpeg -version`)
-  如果是显示相关问题
    -  Shell: Shell 类型 (`echo $SHELL`)
    -  Terminal: 终端类型
-  Others: 其它信息

### 一点点的自我检查

- [x] 充分阅读 [README.md](https://github.com/yutto-dev/bilili) 与[文档](https://bilili.nyakku.moe/)，特别是与本 issue 相关的部分
- [x] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 bilili 本身的问题
- [x] 本 issue 在 [issues](https://github.com/yutto-dev/bilili/issues) 和 [discussion](https://github.com/yutto-dev/bilili/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
![Image](https://github.com/user-attachments/assets/4f56f437-2344-4ba5-8fbf-0b2245ac9d3a)
